### ISSUE TITLE
importSituation

### ISSUE THREAD

**Issue by ElineSchaft** [UMCU-EpiLAB/umcuEpi_acute_ieeg_respect_bids#4]
The function importSituation doesn't work anymore with the new version of fieldtrip (18/11/2020)

**Comment by dvanblooijs** [comment]
with longterm ecog, the quick fix was removing '.json' in line 127 in bids_sidecar.m (in fieldtrip/private/), because it loaded electrodes.json instead of electrodes.tsv. Later this led to the error that electrodes.name could not be found (due to the different content in .json instead of .tsv). Don't know if you have the same error, but this might help.

**Comment by ElineSchaft** [comment]
This is fixed with the new fieldtrip (January 2021).
